spring.application.name=QuizMaster AI
server.port=8080

# Gemini API Configuration
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
# Set your API key here or via environment variable GEMINI_API_KEY
gemini.api.key={Your Key}

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
